import { pageMetadata } from '../../../lib/site';
export const metadata = pageMetadata('Privacy Policy — Korean Classroom Bot', 'Google Classroom data access, storage, Telegram delivery, optional AI processing, and deletion.', '/classroom-bot/privacy/');
export default function ClassroomPrivacy() {
  return <main className="legal shell"><p className="eyebrow">Korean Classroom Bot</p><h1>Privacy Policy</h1><p className="updated">Effective September 23, 2026</p><div className="legal-body">
    <section><h2>Purpose and operator</h2><p>Korean Classroom Bot is a private personal automation tool operated by Gleb Monetchikov, not a public subscription service. It retrieves information from an authorized Google Classroom account and delivers relevant notifications to its authorized user through Telegram.</p></section>
    <section><h2>Google Classroom information</h2><p>The bot reads course identifiers, names and states; coursework titles, descriptions, publication states, deadlines, maximum points, links and timestamps; and announcement text. It processes attached material titles, types and links. It does not download the contents of attached Drive files. Some publication metadata, such as topic identifiers, work type and scheduled time, may be read while synchronizing.</p><p>The requested permissions are:</p><ul><li><code>classroom.courses.readonly</code></li><li><code>classroom.student-submissions.me.readonly</code></li><li><code>classroom.announcements.readonly</code></li></ul><p>The student-submissions permission is used for access to coursework available to the authorized student. The current implementation does not separately retrieve or store student submission records. The bot does not create, modify, submit, grade or delete Google Classroom resources.</p></section>
    <section><h2>Storage and synchronization</h2><p>Supabase stores enabled course records, synchronized coursework and announcements, material metadata, source links and timestamps, content hashes, synchronization events, delivery status, retry counts and error details. Telegram message identifiers and delivery timestamps allow updates to existing notifications and help prevent duplicate delivery. Optional AI enrichment is cached with its content hash and timestamp. Credentials are stored privately by the operator, separately from this website, and used only for authorized service access. The bot does not request or store your Google password.</p></section>
    <section><h2>Telegram delivery</h2><p>Selected Classroom content, source links and optional translations or summaries are formatted and sent to the configured authorized Telegram chat or channel. Edited publications may update existing messages. Content is accessible to members of that destination; the operator is responsible for restricting membership to authorized recipients. Telegram processes delivered messages under its own terms and privacy policy.</p></section>
    <section><h2>Optional DeepSeek processing</h2><p>When the operator enables DeepSeek, coursework titles, descriptions, announcement text and material titles are sent to its API to generate Russian translations, summaries, key points and explicit action lists. Personal information present in that text may therefore also be transmitted. This integration is optional and disabled by default. OAuth credentials and service keys are not included in the enrichment prompt. Authoritative deadlines, Classroom links, identifiers and timestamps come from Classroom; AI output does not replace them. Supabase, Telegram and DeepSeek may process information outside the user’s country.</p></section>
    <section><h2>Use and sharing restrictions</h2><p>Google user data is used only for the described synchronization and notification features. It is not sold or used for advertising or unrelated profiling. Transfers to the described providers are limited to providing these features with the authorized user’s consent. Information received from Google APIs will be used in accordance with the <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, including its Limited Use requirements, and the <a href="https://developers.google.com/workspace/workspace-api-user-data-developer-policy">Google Workspace API user data policy</a>. Google user data must not be used to train generalized AI models. Human access is limited to the authorized user or operator with permission, and the exceptions allowed by these policies, such as security investigation or legal requirements.</p></section>
    <section><h2>Retention, revocation and deletion</h2><p>Stored information is retained only as needed for synchronization, notification delivery, deduplication and the authorized user’s notification history. The current software has no automatic expiry or self-service deletion; the operator reviews retention and manually removes data that is no longer needed. The Google account owner can revoke authorization through <a href="https://myaccount.google.com/connections">Google Account connections</a>. Revocation stops further authorized API access but does not automatically erase existing Supabase records or Telegram messages. Ask the operator to remove stored records, cached enrichment, private OAuth tokens and delivered messages where permitted. Provider copies and backups are subject to their retention practices.</p></section>
    <section><h2>Contact and changes</h2><p>For access, privacy or deletion requests, email Gleb Monetchikov at <a href="mailto:gmonetchikov@gmail.com">gmonetchikov@gmail.com</a>. Do not post Classroom content, credentials or other private information in public GitHub issues. Changes to processing will be reflected here; authorization must be obtained before data is used for a new purpose.</p></section>
  </div></main>;
}
