import Link from 'next/link';
import { pageMetadata } from '../../../lib/site';

export const metadata = pageMetadata('Terms of Service — Korean Classroom Bot', 'Terms for authorized personal use of Korean Classroom Bot and its notifications.', '/classroom-bot/terms/');

export default function ClassroomTerms() {
  return <main className="legal shell"><p className="eyebrow">Korean Classroom Bot</p><h1>Terms of Service</h1><p className="updated">Effective September 23, 2026</p><div className="legal-body">
    <section><h2>About these terms</h2><p>These terms govern use of Korean Classroom Bot, a private personal automation tool operated by Gleb Monetchikov. By using the bot, you agree to these terms. The bot is not a public subscription service and is not affiliated with or endorsed by Google or Telegram.</p></section>
    <section><h2>Purpose and authorized access</h2><p>The bot retrieves coursework and announcements from an authorized Google Classroom account, synchronizes information in Supabase, and delivers notifications to the configured Telegram chat or channel. Google Classroom access is read-only: the bot does not create, modify, submit, grade or delete Classroom resources. Use the bot only with an account and course information you are authorized to access and process.</p></section>
    <section><h2>Your responsibilities</h2><p>Keep your Google and Telegram accounts secure. Only authorize delivery to a chat or channel whose members are permitted to receive the Classroom content. Do not use the bot to bypass access restrictions, disclose another person’s private information without permission, violate applicable law or infringe the rights of teachers, students or other content owners. Do not share passwords, OAuth tokens or service credentials in support requests.</p></section>
    <section><h2>Notifications and optional AI</h2><p>Notifications may be delayed, duplicated, incomplete or unavailable. Optional DeepSeek processing can add translations, summaries, key points and action lists; this output may contain mistakes. Verify assignments and deadlines directly in Google Classroom. Classroom remains the authoritative source for deadlines, links, identifiers and timestamps. The bot does not replace your responsibility to review course announcements or complete and submit assignments.</p></section>
    <section><h2>Privacy and third-party services</h2><p>The <Link href="/classroom-bot/privacy/">Privacy Policy</Link> explains Google authorization, stored information, Telegram delivery, optional DeepSeek processing and deletion. These terms do not authorize data uses beyond that policy or replace any consent required for provider transfers. Google, Supabase, Telegram and DeepSeek operate under their own applicable terms and privacy practices.</p></section>
    <section><h2>Content and intellectual property</h2><p>Classroom content remains subject to the rights of its respective owners. Access through the bot does not grant permission to redistribute course materials or other protected content. The bot’s original software and branding remain subject to their applicable ownership and licence terms.</p></section>
    <section><h2>Availability and ending use</h2><p>The operator may maintain, change, suspend or discontinue this personal automation, including when necessary for security or compliance. Continuous availability or delivery of every notification is not guaranteed. You may stop using the bot and revoke its Google authorization through <a href="https://myaccount.google.com/connections">Google Account connections</a>. Revoking access does not automatically delete existing records or Telegram messages; contact support for deletion as described in the Privacy Policy.</p></section>
    <section><h2>Disclaimers and liability</h2><p>To the extent permitted by applicable law, the bot is provided “as is” and “as available”, without warranties of uninterrupted operation or complete, accurate notifications or AI output. To that same extent, the operator is not responsible for losses resulting from reliance on missed, delayed or inaccurate notifications. Nothing in these terms limits liability or rights that cannot lawfully be limited or excluded.</p></section>
    <section><h2>Changes and contact</h2><p>Updates to these terms will be published here with an effective date. Material changes will be communicated to the authorized user before they take effect. If you do not agree to revised terms, stop using the bot. Questions about these terms or requests to end use can be sent to <a href="mailto:support@hangugo.app">support@hangugo.app</a>.</p></section>
  </div></main>;
}
