import Link from 'next/link';
import { LegalPage } from '../site-components';

export const metadata = { title: 'Privacy Policy — Hangugo', description: 'How Hangugo handles account, learning, analytics, and purchase data.' };

export default function Privacy() {
  return <LegalPage eyebrow="Your data, explained clearly" title="Privacy Policy" updated="August 27, 2026">
    <section><p>This Privacy Policy explains how Hangugo, operated by Gleb Monetchikov (“Hangugo”, “we”, “us”), handles information when you use the Hangugo mobile application and this website.</p></section>
    <section><h2>Information we process</h2><ul><li><strong>Account information.</strong> Hangugo creates an anonymous technical account. If you connect Apple or Google, we receive an account identifier and information made available by that provider, such as your name or email address.</li><li><strong>Learning data.</strong> Studied words, review schedules, practice history, progress, selected learning categories, and app settings.</li><li><strong>AI practice content.</strong> Text submitted for checking, vocabulary supplied to generate exercises, generated tasks, and technical data needed to enforce usage limits and diagnose failures.</li><li><strong>Purchase information.</strong> Product, entitlement, transaction status, and an app user identifier. Hangugo does not receive or store full payment card details.</li><li><strong>Diagnostics and usage data.</strong> App interactions, device and app version information, crash reports, and performance diagnostics in release builds.</li></ul></section>
    <section><h2>How we use information</h2><p>We use this information to provide learning and synchronization features, personalize exercises, maintain subscriptions, prevent abuse, understand feature usage, fix errors, secure the service, and comply with legal obligations. We do not sell personal information or use it for third-party advertising.</p></section>
    <section><h2>Service providers</h2><p>Hangugo relies on service providers that process limited data on our behalf: Google Firebase for authentication, synchronized progress, analytics, and crash reporting; Supabase for application infrastructure and AI-practice access; DeepSeek for generating or evaluating AI practice content; RevenueCat for subscription status; and Apple App Store or Google Play for payment processing. Their processing is governed by their own privacy terms and our service configurations.</p></section>
    <section><h2>Local data and notifications</h2><p>Some learning data and preferences are stored on your device. Learning reminders are scheduled locally after you enable them. You can disable notifications in Hangugo or in your device settings.</p></section>
    <section><h2>Retention and deletion</h2><p>We retain information only as long as reasonably necessary to provide Hangugo, meet legal requirements, resolve disputes, and protect the service. Delete a connected account and synchronized learning data in the app under <strong>Settings → Account &amp; Sync → Delete account and data</strong>. You may also submit a deletion or privacy request through Support.</p></section>
    <section><h2>Security and international processing</h2><p>We use reasonable administrative and technical safeguards. No online service can guarantee absolute security. Our providers may process information in countries other than your own, subject to their applicable safeguards.</p></section>
    <section><h2>Children</h2><p>Hangugo is not directed to children under 13, or the minimum digital-consent age required in their country. We do not knowingly collect personal information from children below that age.</p></section>
    <section><h2>Your choices and rights</h2><p>Depending on your location, you may have rights to access, correct, delete, restrict, or object to processing of your personal information. Submit a request through Hangugo Support. We may need to verify your identity before completing it.</p></section>
    <section><h2>Changes</h2><p>We may update this policy as Hangugo evolves. The effective date above identifies the latest version.</p></section>
    <section><h2>Contact</h2><p>Hangugo is operated by Gleb Monetchikov. For privacy questions or requests, use the contact method on the <Link href="/support/">Support page</Link>.</p></section>
  </LegalPage>;
}
